# Generated by Django 4.2.11 on 2024-09-25 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="item_image",
            field=models.CharField(
                default="https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.freepik.com%2Ffree-photos-vectors%2Fcoming-soon&psig=AOvVaw09YGNyPwzH70a03UnFkvj0&ust=1727323538220000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCPDnuOKb3YgDFQAAAAAdAAAAABAE",
                max_length=500,
            ),
        ),
    ]
