# Generated by Django 4.2.11 on 2024-09-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0002_item_item_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_image",
            field=models.CharField(
                default="https://cdn.pixabay.com/photo/2016/07/26/08/21/coming-soon-1542260_640.png",
                max_length=500,
            ),
        ),
    ]
