# Generated by Django 4.2.11 on 2024-09-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0003_alter_item_item_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_image",
            field=models.CharField(
                default="https://cdn.pixabay.com/photo/2019/12/27/08/36/coming-soon-hour-glass-4721933_1280.png",
                max_length=500,
            ),
        ),
    ]
