# Generated by Django 4.2.11 on 2024-09-25 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0004_alter_item_item_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_image",
            field=models.CharField(
                default="https://t3.ftcdn.net/jpg/00/92/66/20/240_F_92662026_9fiMh5jgCBIo9il3sQgMQCXdZ0W5afBa.jpg",
                max_length=500,
            ),
        ),
    ]
